intermediary/config/routes.rb
Rails.application.routes.draw do
  resources :my_actions
  resources :providers
  get 'welcome/index'
  get 'welcome/search'

  root 'welcome#index'

end

intermediary/app/models/my_action.rb
class MyAction < ActiveRecord::Base
  belongs_to :provider
end

intermediary/app/models/provider.rb
class Provider < ActiveRecord::Base
end

intermediary/app/controllers/my_actions_controller.rb
class MyActionsController < ApplicationController
  before_action :set_my_action, only: [:show, :edit, :update, :destroy]

  # GET /my_actions
  # GET /my_actions.json
  def index
    @my_actions = MyAction.all
  end

  # GET /my_actions/1
  # GET /my_actions/1.json
  def show
  end

  # GET /my_actions/new
  def new
    @my_action = MyAction.new
    @providers = Provider.all
  end

  # GET /my_actions/1/edit
  def edit
  end

  # POST /my_actions
  # POST /my_actions.json
  def create
    @my_action = MyAction.new(my_action_params)

    respond_to do |format|
      if @my_action.save
        format.html { redirect_to @my_action, notice: 'My action was successfully created.' }
        format.json { render :show, status: :created, location: @my_action }
      else
        format.html { render :new }
        format.json { render json: @my_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_actions/1
  # PATCH/PUT /my_actions/1.json
  def update
    respond_to do |format|
      if @my_action.update(my_action_params)
        format.html { redirect_to @my_action, notice: 'My action was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_action }
      else
        format.html { render :edit }
        format.json { render json: @my_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_actions/1
  # DELETE /my_actions/1.json
  def destroy
    @my_action.destroy
    respond_to do |format|
      format.html { redirect_to my_actions_url, notice: 'My action was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_action
      @my_action = MyAction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_action_params
      params.require(:my_action).permit(:name, :url, :active, :provider_id)
    end
end

intermediary/app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:name, :url, :token)
    end
end

intermediary/app/controllers/welcome_controller.rb
require 'open-uri'
class WelcomeController < ApplicationController
	def index
		actions = MyAction.where(name: 'index')
		@products = []
		@products_unite = []
		actions.each do |action|
			@products_unite = JSON.parse(RestClient.get(action.url, { :Authorization => "Token #{action.provider.token}" }))['products']
			@products_unite.each { |p| p['enterprise'] = action.provider.name }
			@products += @products_unite
		end
	end

	def search
		actions = MyAction.where(name: 'search')
		@products = []
		@products_unite = []
		actions.each do |action|

			# render text: action.url
			@products_unite = JSON.parse(RestClient.get(action.url + '?name=' + params[:name], { :Authorization => "Token #{action.provider.token}" }))['products']
			@products_unite.each { |p| p['enterprise'] = action.provider.name }
			@products += @products_unite
			@products = @products.sort_by { |product| product['price'] }
		end
	end
end

intermediary/app/helpers/application_helper.rb
module ApplicationHelper
end

intermediary/app/helpers/my_actions_helper.rb
module MyActionsHelper
end

intermediary/app/helpers/providers_helper.rb
module ProvidersHelper
end

intermediary/app/helpers/welcome_helper.rb
module WelcomeHelper
	def danger?(stock, minimum_stock)
		stock <= minimum_stock ? 'danger' : ''
	end
end

intermediary/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Intermediary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

intermediary/app/views/my_actions/_form.html.erb
<%= form_for(@my_action) do |f| %>
  <% if @my_action.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my_action.errors.count, "error") %> prohibited this my_action from being saved:</h2>

      <ul>
      <% @my_action.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :provider_id %><br>
    <%= f.select :provider_id, options_from_collection_for_select(@providers, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

intermediary/app/views/my_actions/edit.html.erb
<h1>Editing My Action</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_action %> |
<%= link_to 'Back', my_actions_path %>

intermediary/app/views/my_actions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing My Actions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Active</th>
      <th>Provider</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_actions.each do |my_action| %>
      <tr>
        <td><%= my_action.name %></td>
        <td><%= my_action.url %></td>
        <td><%= my_action.active %></td>
        <td><%= my_action.provider.name %></td>
        <td><%= link_to 'Show', my_action %></td>
        <td><%= link_to 'Edit', edit_my_action_path(my_action) %></td>
        <td><%= link_to 'Destroy', my_action, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My action', new_my_action_path %>

intermediary/app/views/my_actions/new.html.erb
<h1>New My Action</h1>

<%= render 'form' %>

<%= link_to 'Back', my_actions_path %>

intermediary/app/views/my_actions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @my_action.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @my_action.url %>
</p>

<p>
  <strong>Active:</strong>
  <%= @my_action.active %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @my_action.provider %>
</p>

<%= link_to 'Edit', edit_my_action_path(@my_action) %> |
<%= link_to 'Back', my_actions_path %>

intermediary/app/views/providers/_form.html.erb
<%= form_for(@provider) do |f| %>
  <% if @provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
      <% @provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :token %><br>
    <%= f.text_field :token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

intermediary/app/views/providers/edit.html.erb
<h1>Editing Provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

intermediary/app/views/providers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Providers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @providers.each do |provider| %>
      <tr>
        <td><%= provider.name %></td>
        <td><%= provider.url %></td>
        <td><%= provider.token %></td>
        <td><%= link_to 'Show', provider %></td>
        <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
        <td><%= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Provider', new_provider_path %>

intermediary/app/views/providers/new.html.erb
<h1>New Provider</h1>

<%= render 'form' %>

<%= link_to 'Back', providers_path %>

intermediary/app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @provider.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @provider.url %>
</p>

<p>
  <strong>Token:</strong>
  <%= @provider.token %>
</p>

<%= link_to 'Edit', edit_provider_path(@provider) %> |
<%= link_to 'Back', providers_path %>

intermediary/app/views/welcome/index.html.erb
<table class="table table-striped table-fixedheader">
	<thead>
		<tr>
			<th>Nombre</th>
			<th>Descripción</th>
			<th>Categoría</th>
			<th>SubCategoría</th>
			<th>Marca</th>
			<th>Precio</th>
			<th>Stock</th>
			<th>Stock mínimo</th>
		</tr>
	</thead>
	<tbody>
		<% @products.each do |product| %>
		<tr>
			<td><%= product['name'] rescue 'error' %></td>
			<td><%= product['description'] rescue 'error' %></td>		
			<td><%= product['category'] rescue 'error' %></td>
			<td><%= product['sub_category'] rescue 'error' %></td>
			<td><%= product['brand'] rescue 'error' %></td>
			<td><%= product['price'] rescue 'error' %></td>
			<td><%= product['stock'] rescue 'error' %></td>
			<td><%= product['minimum_stock'] rescue 'error' %></td>
		</tr>
		<% end %>
	</tbody>
</table>

intermediary/app/views/welcome/search.html.erb
<table class="table table-striped">
	<thead>
		<tr>
			<th>Nombre</th>
			<th>Descripción</th>
			<th>Empresa</th>
			<th>Categoría</th>
			<th>SubCategoría</th>
			<th>Marca</th>
			<th>Precio</th>
			<th>Stock</th>
			<th>Stock mínimo</th>
		</tr>
	</thead>
	<tbody>
		<% @products.each do |product| %>
		<tr class="<%= danger?(product['stock'].to_i, product['minimum_stock'].to_i) %>">
			<td><%= product['name'] rescue 'error' %></td>
			<td><%= product['description'] rescue 'error' %></td>
			<td><%= product['enterprise'] %></td>	
			<td><%= product['category'] rescue 'error' %></td>
			<td><%= product['sub_category'] rescue 'error' %></td>
			<td><%= product['brand'] rescue 'error' %></td>
			<td><%= product['price'] rescue 'error' %></td>
			<td><%= product['stock'] rescue 'error' %></td>
			<td><%= product['minimum_stock'] rescue 'error' %></td>
		</tr>
		<% end %>
	</tbody>
</table>